name: Build package pip

on: 
  push:
    branches: [dev_wd]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        $CONDA/bin/conda install -y -n base -c conda-forge mamba
        $CONDA/bin/conda create -n foo -q --yes --quiet -c conda-forge -c bioconda snakemake=6.2.1 fuzzywuzzy mock sphinx sphinx-argparse sphinx_rtd_theme flake8 coreutils mamba python=3.9
        $CONDA/bin/conda run -n foo python -m pip install . --no-deps --ignore-installed -vvv
    - name: build envs
      run: |
        $CONDA/bin/conda run -n foo snakePipes createEnvs --force --condaDir $CONDA/envs/
    - name: Run CI
      run: |
        ./.ci_stuff/test_dag.sh
    - name: Docs
      run: |
        cd docs
        make html

